### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kassane** [kassane/docker-zig#2]
Currently, only a few images were posted on the hub, which will have to be updated and corrected.

### Need fix

- [x] #1 
- [x] alpine, missing workdir (user r/w access)

### TODO list

- [ ] add: [zig w/ MSVC (xwin)](https://github.com/kassane/xwin-zig-test)
- [x] Add more architectures
- [ ] organize images tag
- [ ] add: more options in docker-hub

Any help is appreciated!
